# Generated by Django 4.2.1 on 2023-05-18 02:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.customUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(default='university', max_length=250, verbose_name='name of school'),
        ),
    ]
