# Generated by Django 4.2.1 on 2023-05-25 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='student name')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256, verbose_name='subject title')),
                ('grade', models.CharField(blank=True, max_length=1, verbose_name='grade for the course')),
                ('level', models.CharField(max_length=15, verbose_name='Ordinary or advanced Level')),
                ('education', models.CharField(max_length=25, verbose_name='Education type, grammar, technical or commercial')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gce.student')),
            ],
        ),
    ]
