# Generated by Django 4.2.1 on 2023-07-08 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gce", "0003_rename_institution_institution_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="institution",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
