# Generated by Django 4.2.1 on 2023-07-08 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gce", "0004_institution_created_at_institution_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admissionrequirement",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admission_requirements",
                to="gce.institution",
            ),
        ),
    ]
