# Generated by Django 4.2.1 on 2023-07-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gce", "0005_alter_admissionrequirement_institution"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="purpose",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Purpose of the setring requirement",
            ),
        ),
    ]
