# Generated by Django 4.2.1 on 2023-07-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gce", "0006_institution_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="level",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Level of requirement: Advanced or Ordinary",
            ),
        ),
    ]
