# Generated by Django 4.2.1 on 2023-07-15 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gce", "0008_remove_result_education_remove_result_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admissionrequirement",
            name="creator_id",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_user",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="certificate",
            name="id",
            field=models.CharField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Unique id of certificate",
            ),
        ),
    ]
