# Generated by Django 4.2.1 on 2023-07-15 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gce", "0009_admissionrequirement_creator_id_alter_certificate_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admissionrequirement",
            name="creator_id",
        ),
        migrations.AddField(
            model_name="admissionrequirement",
            name="user_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="institute_req",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
