# Generated by Django 4.2.1 on 2023-07-16 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gce", "0013_remove_institution_user_id_institution_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="institution",
            options={"ordering": ["id"]},
        ),
    ]
